/** Turkish-market mock job listings for dashboard and API fallbacks */

export type MockJob = {
  id: string
  title: string
  company: string
  location: string
  type: string
  salary: string
  posted: string
  requiredSkills: string[]
  fallbackMatched: string[]
  fallbackMissing: string[]
  fallbackMatch: number
}

export const MOCK_JOBS_TR: MockJob[] = [
  {
    id: "Senior Frontend Engineer-Trendyol",
    title: "Senior Frontend Engineer",
    company: "Trendyol",
    location: "Uzaktan · Türkiye",
    type: "Tam zamanlı",
    salary: "₺95.000 – ₺125.000 / ay",
    posted: "2 gün önce",
    requiredSkills: ["React", "TypeScript", "Next.js", "Tailwind", "Testing", "GraphQL", "Playwright"],
    fallbackMatched: ["React", "TypeScript", "Next.js", "Tailwind", "Testing"],
    fallbackMissing: ["GraphQL", "Playwright"],
    fallbackMatch: 92,
  },
  {
    id: "Full-Stack Engineer, Platform-Getir",
    title: "Full-Stack Engineer, Platform",
    company: "Getir",
    location: "İstanbul, Türkiye",
    type: "Hibrit",
    salary: "₺110.000 – ₺140.000 / ay",
    posted: "5 gün önce",
    requiredSkills: ["Node.js", "PostgreSQL", "React", "AWS", "Kubernetes", "gRPC", "Terraform"],
    fallbackMatched: ["Node.js", "PostgreSQL", "React", "AWS"],
    fallbackMissing: ["Kubernetes", "gRPC", "Terraform"],
    fallbackMatch: 86,
  },
  {
    id: "Data Analyst-ArgeTech Yazılım",
    title: "Data Analyst",
    company: "ArgeTech Yazılım",
    location: "Ankara, Türkiye",
    type: "Tam zamanlı",
    salary: "₺70.000 – ₺90.000 / ay",
    posted: "1 gün önce",
    requiredSkills: ["Python", "SQL", "Pandas", "Tableau", "Statistics", "dbt"],
    fallbackMatched: ["SQL", "Tableau"],
    fallbackMissing: ["Python", "Pandas", "Statistics", "dbt"],
    fallbackMatch: 58,
  },
  {
    id: "Machine Learning Engineer-Eczacıbaşı",
    title: "Machine Learning Engineer",
    company: "Eczacıbaşı",
    location: "İstanbul, Türkiye",
    type: "Hibrit",
    salary: "₺120.000 – ₺155.000 / ay",
    posted: "3 gün önce",
    requiredSkills: ["Python", "Machine Learning", "PyTorch", "TensorFlow", "MLOps", "AWS", "SQL"],
    fallbackMatched: ["Python", "SQL", "AWS"],
    fallbackMissing: ["Machine Learning", "PyTorch", "TensorFlow", "MLOps"],
    fallbackMatch: 62,
  },
  {
    id: "Frontend Engineer, Design Systems-Softtech",
    title: "Frontend Engineer, Design Systems",
    company: "Softtech",
    location: "Uzaktan · Türkiye",
    type: "Sözleşmeli",
    salary: "₺800 – ₺1.100 / saat",
    posted: "Bugün",
    requiredSkills: ["React", "Storybook", "Accessibility", "Tailwind", "Design tokens", "Figma API"],
    fallbackMatched: ["React", "Storybook", "Accessibility", "Tailwind"],
    fallbackMissing: ["Design tokens", "Figma API"],
    fallbackMatch: 88,
  },
  {
    id: "AI Research Engineer-BulutÇözüm Teknolojileri",
    title: "AI Research Engineer",
    company: "BulutÇözüm Teknolojileri",
    location: "İzmir, Türkiye",
    type: "Tam zamanlı",
    salary: "₺130.000 – ₺175.000 / ay",
    posted: "4 gün önce",
    requiredSkills: ["Python", "Deep Learning", "Machine Learning", "PyTorch", "NLP", "Research"],
    fallbackMatched: ["Python"],
    fallbackMissing: ["Deep Learning", "Machine Learning", "PyTorch", "NLP", "Research"],
    fallbackMatch: 48,
  },
  {
    id: "Software Engineer, Growth-Yemeksepeti",
    title: "Software Engineer, Growth",
    company: "Yemeksepeti",
    location: "İstanbul, Türkiye",
    type: "Uzaktan",
    salary: "₺90.000 – ₺110.000 / ay",
    posted: "1 hafta önce",
    requiredSkills: ["Node.js", "React", "GraphQL", "Tailwind", "Firebase"],
    fallbackMatched: ["Node.js", "React"],
    fallbackMissing: ["GraphQL", "Tailwind", "Firebase"],
    fallbackMatch: 45,
  },
  {
    id: "Senior Backend Developer-Aselsan",
    title: "Senior Backend Developer",
    company: "Aselsan",
    location: "Ankara, Türkiye",
    type: "Hibrit",
    salary: "₺105.000 – ₺130.000 / ay",
    posted: "1 saat önce",
    requiredSkills: ["Go", "Node.js", "Microservices", "Docker", "AWS", "gRPC"],
    fallbackMatched: ["Node.js", "Docker", "AWS"],
    fallbackMissing: ["Go", "Microservices", "gRPC"],
    fallbackMatch: 50,
  },
  {
    id: "Lead Frontend Engineer-Turkcell",
    title: "Lead Frontend Engineer",
    company: "Turkcell",
    location: "İstanbul, Türkiye",
    type: "Tam zamanlı",
    salary: "₺115.000 – ₺145.000 / ay",
    posted: "2 saat önce",
    requiredSkills: ["Next.js", "React", "TypeScript", "Vercel SDK", "Performance", "CSS"],
    fallbackMatched: ["Next.js", "React", "TypeScript", "CSS"],
    fallbackMissing: ["Vercel SDK", "Performance"],
    fallbackMatch: 85,
  },
  {
    id: "Staff Data Scientist-Hepsiburada",
    title: "Staff Data Scientist",
    company: "Hepsiburada",
    location: "İstanbul, Türkiye",
    type: "Tam zamanlı",
    salary: "₺125.000 – ₺165.000 / ay",
    posted: "5 saat önce",
    requiredSkills: ["Python", "TensorFlow", "Generative AI", "LLM", "SQL", "Spark"],
    fallbackMatched: ["Python", "SQL"],
    fallbackMissing: ["TensorFlow", "Generative AI", "LLM", "Spark"],
    fallbackMatch: 40,
  },
  {
    id: "Full Stack Developer-Papara",
    title: "Full Stack Developer",
    company: "Papara",
    location: "Uzaktan · Türkiye",
    type: "Tam zamanlı",
    salary: "₺100.000 – ₺130.000 / ay",
    posted: "12 saat önce",
    requiredSkills: ["Ruby", "React", "TypeScript", "PostgreSQL", "Kafka"],
    fallbackMatched: ["React", "TypeScript", "PostgreSQL"],
    fallbackMissing: ["Ruby", "Kafka"],
    fallbackMatch: 65,
  },
  {
    id: "DevOps Engineer-İş Bankası Teknoloji",
    title: "DevOps Engineer",
    company: "İş Bankası Teknoloji",
    location: "İstanbul, Türkiye",
    type: "Sözleşmeli",
    salary: "₺550 – ₺750 / saat",
    posted: "1 gün önce",
    requiredSkills: ["CI/CD", "Kubernetes", "AWS", "Terraform", "Go"],
    fallbackMatched: ["AWS"],
    fallbackMissing: ["CI/CD", "Kubernetes", "Terraform", "Go"],
    fallbackMatch: 25,
  },
  {
    id: "Android Engineer-BiTaksi",
    title: "Android Engineer",
    company: "BiTaksi",
    location: "İstanbul, Türkiye",
    type: "Ofisten",
    salary: "₺85.000 – ₺105.000 / ay",
    posted: "1 gün önce",
    requiredSkills: ["Kotlin", "Android SDK", "Java", "Jetpack Compose", "Coroutines"],
    fallbackMatched: ["Java"],
    fallbackMissing: ["Kotlin", "Android SDK", "Jetpack Compose", "Coroutines"],
    fallbackMatch: 20,
  },
  {
    id: "iOS Developer-Migros Teknoloji",
    title: "iOS Developer",
    company: "Migros Teknoloji",
    location: "Bursa, Türkiye",
    type: "Hibrit",
    salary: "₺95.000 – ₺120.000 / ay",
    posted: "2 gün önce",
    requiredSkills: ["Swift", "Objective-C", "iOS SDK", "Combine", "XCode"],
    fallbackMatched: [],
    fallbackMissing: ["Swift", "Objective-C", "iOS SDK", "Combine", "XCode"],
    fallbackMatch: 10,
  },
  {
    id: "Cloud Architect-Türk Telekom",
    title: "Cloud Architect",
    company: "Türk Telekom",
    location: "Ankara, Türkiye",
    type: "Tam zamanlı",
    salary: "₺120.000 – ₺160.000 / ay",
    posted: "2 gün önce",
    requiredSkills: ["AWS", "System Design", "Kubernetes", "Python", "Networking"],
    fallbackMatched: ["AWS", "Python", "System Design"],
    fallbackMissing: ["Kubernetes", "Networking"],
    fallbackMatch: 60,
  },
  {
    id: "Product Engineer-Garanti BBVA Teknoloji",
    title: "Product Engineer",
    company: "Garanti BBVA Teknoloji",
    location: "İstanbul, Türkiye",
    type: "Hibrit",
    salary: "₺95.000 – ₺125.000 / ay",
    posted: "3 gün önce",
    requiredSkills: ["React", "TypeScript", "Node.js", "CSS", "Figma", "Redux"],
    fallbackMatched: ["React", "TypeScript", "Node.js", "CSS"],
    fallbackMissing: ["Figma", "Redux"],
    fallbackMatch: 80,
  },
  {
    id: "Security Engineer-Netaş",
    title: "Security Engineer",
    company: "Netaş",
    location: "Kocaeli, Türkiye",
    type: "Tam zamanlı",
    salary: "₺90.000 – ₺115.000 / ay",
    posted: "4 gün önce",
    requiredSkills: ["Security", "Rust", "Go", "Cryptography", "Linux", "Networking"],
    fallbackMatched: ["Linux"],
    fallbackMissing: ["Security", "Rust", "Go", "Cryptography", "Networking"],
    fallbackMatch: 30,
  },
  {
    id: "Backend Lead-Peak Games",
    title: "Backend Lead",
    company: "Peak Games",
    location: "İstanbul, Türkiye",
    type: "Tam zamanlı",
    salary: "₺115.000 – ₺145.000 / ay",
    posted: "5 gün önce",
    requiredSkills: ["Rust", "Elixir", "PostgreSQL", "Kafka", "Cassandra", "C++"],
    fallbackMatched: ["PostgreSQL"],
    fallbackMissing: ["Rust", "Elixir", "Kafka", "Cassandra", "C++"],
    fallbackMatch: 20,
  },
  {
    id: "Frontend Engineer-Insider",
    title: "Frontend Engineer",
    company: "Insider",
    location: "Uzaktan · Türkiye",
    type: "Tam zamanlı",
    salary: "₺90.000 – ₺115.000 / ay",
    posted: "1 hafta önce",
    requiredSkills: ["React", "TypeScript", "WebGL", "C++", "Canvas API"],
    fallbackMatched: ["React", "TypeScript"],
    fallbackMissing: ["WebGL", "C++", "Canvas API"],
    fallbackMatch: 50,
  },
  {
    id: "React Native Developer-Turkcell Dijital",
    title: "React Native Developer",
    company: "Turkcell Dijital",
    location: "İstanbul, Türkiye",
    type: "Hibrit",
    salary: "₺100.000 – ₺130.000 / ay",
    posted: "1 hafta önce",
    requiredSkills: ["React Native", "TypeScript", "Redux", "GraphQL", "iOS", "Android"],
    fallbackMatched: ["TypeScript", "GraphQL"],
    fallbackMissing: ["React Native", "Redux", "iOS", "Android"],
    fallbackMatch: 45,
  },
  {
    id: "AI Prompt Engineer-Arçelik Global",
    title: "AI Prompt Engineer",
    company: "Arçelik Global",
    location: "İstanbul, Türkiye",
    type: "Tam zamanlı",
    salary: "₺85.000 – ₺110.000 / ay",
    posted: "2 hafta önce",
    requiredSkills: ["Python", "Prompt Engineering", "LLM", "NLP", "Writing"],
    fallbackMatched: ["Python", "Writing"],
    fallbackMissing: ["Prompt Engineering", "LLM", "NLP"],
    fallbackMatch: 55,
  },
]

export const MOCK_INTERNSHIPS_TR: MockJob[] = [
  {
    id: "Data Analyst Intern-Turkcell",
    title: "Data Analyst Intern",
    company: "Turkcell",
    location: "Ankara, Türkiye",
    type: "Staj",
    salary: "₺45.000 – ₺55.000 / ay",
    posted: "1 gün önce",
    requiredSkills: ["Python", "SQL", "Pandas", "Tableau", "Statistics", "Machine Learning"],
    fallbackMatched: ["SQL", "Tableau"],
    fallbackMissing: ["Python", "Pandas", "Statistics", "Machine Learning"],
    fallbackMatch: 65,
  },
  {
    id: "Machine Learning Intern-TÜBİTAK BİLGEM",
    title: "Machine Learning Intern",
    company: "TÜBİTAK BİLGEM",
    location: "Kocaeli, Türkiye",
    type: "Staj",
    salary: "₺50.000 – ₺65.000 / ay",
    posted: "3 saat önce",
    requiredSkills: ["Python", "Machine Learning", "PyTorch", "TensorFlow", "Deep Learning", "NLP"],
    fallbackMatched: ["Python"],
    fallbackMissing: ["Machine Learning", "PyTorch", "TensorFlow", "Deep Learning", "NLP"],
    fallbackMatch: 72,
  },
  {
    id: "Software Engineer Intern-Aselsan",
    title: "Software Engineer Intern",
    company: "Aselsan",
    location: "Ankara, Türkiye",
    type: "Staj",
    salary: "₺48.000 – ₺60.000 / ay",
    posted: "2 gün önce",
    requiredSkills: ["Java", "C++", "AWS", "Data Structures", "Algorithms", "Object-Oriented Design"],
    fallbackMatched: ["Data Structures", "Algorithms"],
    fallbackMissing: ["Java", "C++", "AWS", "Object-Oriented Design"],
    fallbackMatch: 80,
  },
]
